name: ui
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.10.0 <4.0.0"

description: UI layer (widgets, screens).

dependencies:
  core:
    path: ../core
  viewmodel:
    path: ../viewmodel
  freezed_annotation: ^3.1.0
  webview_flutter: ^4.8.0
  flutter_hooks: ^0.21.2
  go_router: ^17.0.0
  modal_bottom_sheet: ^3.0.0
  mobile_scanner: ^7.0.1
  transparent_image: ^2.0.1
  auto_size_text: ^3.0.0
  package_info_plus: ^9.0.0
  flutter_svg: ^2.0.10+1
  image_picker: ^1.1.2
  file_picker: ^8.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/

dev_dependencies:
  go_router_builder: any
  build_runner: ^2.4.9
  freezed: ^3.1.0
  source_gen: ^4.2.2
  analyzer: ^8.4.1
